### ISSUE TITLE
Queue <-> Judgeの通信について考える

### ISSUE THREAD

**Issue by comavius** [traP-jp/traO-Judge-docs#179]

**Comment by comavius** [comment]
Judgeからリソースの取得と解放を送りたい

**Comment by ZOI-dayo** [comment]
「Queueがジャッジリクエストが要求するファイルを(オブジェクトストレージからコピーして)準備する」
→「QueueがJudgeを起動」
→「ジャッジ完了、Judge -> Queueの通信で結果が報告される」
→「QueueはJudgeを終了、不要なファイルが発生しているならばそれを削除」

とすればJudgeはリソース管理しなくてもいいのかな? と思います

**Comment by comavius** [comment]
1提出ごとにjudgeとexec-containerの入ったpodの起動と削除をするなら、一時的に使うファイルはそのpodのemptyDirに入れておけばいいので、不要なファイルの削除をQueueに持たせる必要もなさそうです。
