### ISSUE TITLE
ブランチの命名規則などをまとめる

### ISSUE THREAD

**Issue by comavius** [traP-jp/traO-Judge-docs#6]
@kenken714 これすでにどこかに書いてあったりしますか？なさそうならやります。

**Comment by kenken714** [comment]
ありません、お願いします

**Comment by kenken714** [comment]
流石に投げ過ぎか

**Comment by kenken714** [comment]
ブランチ戦略をまとめて記述したいです
v0ではmain←develop←feature
ブランチの命名規則は(feat|fix|chore|refactor)/#{issue_id}-{name}
